# Generated by Django 3.2.4 on 2021-06-29 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0002_alter_tournament_arbiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[(1, 'Biale'), (2, 'Remis'), (3, 'Czarne')], max_length=6)),
                ('black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_black', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
